spring:
  application:
    name: flix

  datasource:
    url: jdbc:postgresql://localhost:5432/flix
    username: danilo
    password: danilo
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  flyway:
    enabled: true

flix:
  security:
    secret: palavra-secreta